version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts-list
    volumes:
      - C:\Users\Константи\Downloads\contacts-list\contacts-list\init.sql:/docker-entrypoint-initdb.d/init.sql